name: Build

on:
  push:
    branches:
    - 'develop'

jobs:
  build:
    runs-on: rocker/tidyverse
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    - 
      name: install R reqs
      run: |
        Rscript -e 'install.packages("pagedown")'
        Rscript -e 'remotes::install_github("mitchelloharawild/icons@v0.1.0")'
    - 
      name: install ubuntu reqs
      run: |
        apt update -qq && apt-get install -y -qq --no-install-recommends libz-dev libpoppler-cpp-dev pandoc curl
    -
      name: install chrome
      run: |
        curl -L https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -o /usr/local/chrome.deb && apt-get -y install /usr/local/chrome.deb
    -
      name: create artifacts
      run: |
        cd datadrivencv
        R CMD build datadrivencv    
        R CMD INSTALL datadrivencv
